// ====== 实体类 ======

class Plant{
constructor(t,r,c){const d=C.plants[t];this.type=t;this.row=r;this.col=c;this.hp=d.hp;this.maxHp=d.hp;this.lastShoot=0;this.lastSun=0;this.af=0;this.at=0;this.boosted=0;this.armed=0;this.done=false}
get x(){return C.grid.ox+this.col*C.grid.cw+C.grid.cw/2}
get y(){return C.grid.oy+this.row*C.grid.ch+C.grid.ch/2}
update(dt,g){this.at+=dt;if(this.at>100){this.af=(this.af+1)%60;this.at=0};if(this.boosted>0)this.boosted=Math.max(0,this.boosted-dt);const d=C.plants[this.type];if(this.type==='sunflower'){if(g.time-this.lastSun>=g.cfg.sfInt){this.lastSun=g.time;g.suns.push(new Sun(this.x,this.y-40,0,g))}}else if(d.cat==='shooter'){const iv=this.boosted>0?d.si*0.5:d.si;if(g.zombies.some(z=>z.row===this.row&&z.x>this.x&&z.hp>0)&&g.time-this.lastShoot>=iv){this.lastShoot=g.time;g.projs.push(new Proj(this.x+20,this.y-4,this.row,this.type==='snowpea'))}}else if(this.type==='potatomine'&&!this.done){if(!this.armed)this.armed+=dt;else this.armed=Math.min(this.armed+dt,C.plants.potatomine.arm);if(this.armed>=C.plants.potatomine.arm){for(const z of g.zombies){if(z.row===this.row&&Math.abs(z.x-this.x)<C.grid.cw/2){z.takeDamage(1e4);this.done=true;g.hitEff.push({x:this.x,y:this.y,t:400,color:'#ef4444',big:true});return}}}}}
draw(c){if(this.done)return;const d=C.plants[this.type];c.save();const gr=c.createRadialGradient(this.x,this.y+15,2,this.x,this.y+15,25);gr.addColorStop(0,d.color+'40');gr.addColorStop(1,d.color+'00');c.fillStyle=gr;c.beginPath();c.arc(this.x,this.y+15,25,0,Math.PI*2);c.fill();const b=Math.sin(this.af*0.15)*2;this.drawBody(c,b,d);if(this.boosted>0){c.strokeStyle='#a78bfa';c.lineWidth=2;c.shadowColor='#a78bfa';c.shadowBlur=10;c.beginPath();c.arc(this.x,this.y,28,0,Math.PI*2);c.stroke();c.shadowBlur=0};c.restore();if(this.hp<this.maxHp&&this.type!=='cherrybomb'&&this.type!=='potatomine'){const bw=50,bh=5,bx=this.x-bw/2,by=this.y-45,r=this.hp/this.maxHp;c.fillStyle='rgba(0,0,0,.5)';c.roundRect(bx,by,bw,bh,3);c.fill();c.fillStyle=r>.5?'#4ade80':r>.25?'#fbbf24':'#f87171';c.roundRect(bx,by,bw*r,bh,3);c.fill()}}
drawBody(c,b,d){
if(this.type==='sunflower'){const sx=this.x,sy=this.y+b;c.strokeStyle='#4a7f2c';c.lineWidth=4;c.beginPath();c.moveTo(sx,sy+10);c.lineTo(sx,sy+35);c.stroke();c.fillStyle='#4a7f2c';c.beginPath();c.ellipse(sx-8,sy+22,8,4,-.3,0,Math.PI*2);c.fill();c.beginPath();c.ellipse(sx+8,sy+28,8,4,.3,0,Math.PI*2);c.fill();for(let i=0;i<10;i++){const a=i/10*Math.PI*2;c.fillStyle=i%2===0?'#facc15':'#f59e0b';c.beginPath();c.ellipse(sx+Math.cos(a)*18,sy+Math.sin(a)*18,10,5,a,0,Math.PI*2);c.fill()};c.fillStyle='#92400e';c.beginPath();c.arc(sx,sy,10,0,Math.PI*2);c.fill();c.fillStyle='#78350f';c.beginPath();c.arc(sx-3,sy-3,3,0,Math.PI*2);c.fill();c.beginPath();c.arc(sx+4,sy+2,2.5,0,Math.PI*2);c.fill();c.beginPath();c.arc(sx+2,sy-4,2.5,0,Math.PI*2);c.fill()}
else if(this.type==='peashooter'){const px=this.x,py=this.y+b;c.strokeStyle='#4a7f2c';c.lineWidth=4;c.beginPath();c.moveTo(px,py+5);c.lineTo(px,py+35);c.stroke();c.fillStyle='#4a7f2c';c.beginPath();c.ellipse(px-10,py+20,10,4,-.3,0,Math.PI*2);c.fill();c.beginPath();c.ellipse(px+10,py+28,10,4,.3,0,Math.PI*2);c.fill();c.fillStyle='#22c55e';c.beginPath();c.arc(px,py,20,0,Math.PI*2);c.fill();c.fillStyle='rgba(255,255,255,.2)';c.beginPath();c.arc(px-6,py-6,7,0,Math.PI*2);c.fill();c.fillStyle='#16a34a';c.beginPath();c.ellipse(px+18,py,10,6,0,0,Math.PI*2);c.fill();c.fillStyle='#fff';c.beginPath();c.arc(px+6,py-6,8,0,Math.PI*2);c.fill();c.beginPath();c.arc(px-6,py-6,8,0,Math.PI*2);c.fill();c.fillStyle='#1a1a2e';c.beginPath();c.arc(px+8,py-6,4,0,Math.PI*2);c.fill();c.beginPath();c.arc(px-4,py-6,4,0,Math.PI*2);c.fill()}
else if(this.type==='wallnut'){const wx=this.x,wy=this.y+b,r=this.hp/this.maxHp;c.fillStyle=r>.6?'#a16207':r>.3?'#854d0e':'#713f12';c.beginPath();c.ellipse(wx,wy,28,32,0,0,Math.PI*2);c.fill();c.fillStyle='rgba(255,255,255,.15)';c.beginPath();c.ellipse(wx-8,wy-8,12,14,0,0,Math.PI*2);c.fill();if(r<.6){c.strokeStyle='#451a03';c.lineWidth=2;c.beginPath();c.moveTo(wx-5,wy-15);c.lineTo(wx+3,wy-5);c.lineTo(wx-2,wy+5);c.stroke()};if(r<.3){c.beginPath();c.moveTo(wx+8,wy-10);c.lineTo(wx+2,wy);c.lineTo(wx+10,wy+8);c.stroke()};c.fillStyle='#451a03';if(r>.6){c.beginPath();c.arc(wx,wy+5,8,.1,Math.PI-.1);c.stroke()}else if(r>.3){c.beginPath();c.moveTo(wx-6,wy+5);c.lineTo(wx+6,wy+5);c.stroke()}else{c.beginPath();c.arc(wx,wy+12,6,Math.PI+.3,-.3);c.stroke()};c.fillRect(wx-10,wy-10,5,5);c.fillRect(wx+5,wy-10,5,5)}
else if(this.type==='snowpea'){const sx=this.x,sy=this.y+b;c.strokeStyle='#4a7f2c';c.lineWidth=4;c.beginPath();c.moveTo(sx,sy+5);c.lineTo(sx,sy+35);c.stroke();c.fillStyle='#4a7f2c';c.beginPath();c.ellipse(sx-10,sy+20,10,4,-.3,0,Math.PI*2);c.fill();c.beginPath();c.ellipse(sx+10,sy+28,10,4,.3,0,Math.PI*2);c.fill();c.fillStyle='#93c5fd';c.beginPath();c.arc(sx,sy,20,0,Math.PI*2);c.fill();c.fillStyle='rgba(255,255,255,.25)';c.beginPath();c.arc(sx-5,sy-6,8,0,Math.PI*2);c.fill();c.fillStyle='rgba(255,255,255,.1)';for(let i=0;i<6;i++){const a=i/6*Math.PI*2;c.beginPath();c.arc(sx+Math.cos(a)*15,sy+Math.sin(a)*15,4,0,Math.PI*2);c.fill()};c.fillStyle='#60a5fa';c.beginPath();c.ellipse(sx+18,sy,10,6,0,0,Math.PI*2);c.fill();c.fillStyle='#fff';c.beginPath();c.arc(sx+6,sy-6,7,0,Math.PI*2);c.fill();c.beginPath();c.arc(sx-6,sy-6,7,0,Math.PI*2);c.fill();c.fillStyle='#1e3a5f';c.beginPath();c.arc(sx+8,sy-6,3.5,0,Math.PI*2);c.fill();c.beginPath();c.arc(sx-4,sy-6,3.5,0,Math.PI*2);c.fill();c.fillStyle='rgba(255,255,255,.4)';const pa=this.af*.05;for(let i=0;i<3;i++){const a=pa+i*Math.PI*2/3;c.beginPath();c.arc(sx+Math.cos(a)*24,sy-10+Math.sin(a)*8,2,0,Math.PI*2);c.fill()}}
else if(this.type==='potatomine'){const mx=this.x,my=this.y+b,arm=this.armed>=C.plants.potatomine.arm;c.fillStyle=arm?'#dc2626':'#92400e';c.beginPath();c.ellipse(mx,my,22,18,0,0,Math.PI*2);c.fill();c.fillStyle='rgba(255,255,255,.1)';c.beginPath();c.ellipse(mx-5,my-5,10,8,0,0,Math.PI*2);c.fill();if(arm){c.fillStyle='#ef4444';c.shadowColor='#ef4444';c.shadowBlur=8;c.beginPath();c.arc(mx-6,my-6,2,0,Math.PI*2);c.fill();c.beginPath();c.arc(mx+5,my-8,2,0,Math.PI*2);c.fill();c.beginPath();c.arc(mx,my-10,2,0,Math.PI*2);c.fill();c.shadowBlur=0;c.strokeStyle='#ef4444';c.lineWidth=1;c.beginPath();c.arc(mx,my-2,12,.3,Math.PI-.3);c.stroke()}else{c.fillStyle='#451a03';c.beginPath();c.arc(mx-4,my-6,2,0,Math.PI*2);c.fill();c.beginPath();c.arc(mx+4,my-6,2,0,Math.PI*2);c.fill()};if(this.armed<C.plants.potatomine.arm&&this.armed>0){const p=this.armed/C.plants.potatomine.arm;c.fillStyle='rgba(255,255,255,.3)';c.roundRect(mx-10,my+14,20*p,3,2);c.fill()}}
else if(this.type==='cherrybomb'){const cx=this.x,cy=this.y+b;c.fillStyle='#ef4444';c.beginPath();c.arc(cx,cy,20,0,Math.PI*2);c.fill();c.fillStyle='rgba(255,255,255,.2)';c.beginPath();c.arc(cx-5,cy-6,7,0,Math.PI*2);c.fill();c.fillStyle='#b91c1c';c.beginPath();c.moveTo(cx,cy-18);c.lineTo(cx-6,cy-8);c.lineTo(cx+6,cy-8);c.closePath();c.fill();c.fillStyle='#fff';c.beginPath();c.arc(cx-6,cy-3,3,0,Math.PI*2);c.fill();c.beginPath();c.arc(cx+6,cy-3,3,0,Math.PI*2);c.fill();c.fillStyle='#1a1a2e';c.beginPath();c.arc(cx-5,cy-3,1.5,0,Math.PI*2);c.fill();c.beginPath();c.arc(cx+7,cy-3,1.5,0,Math.PI*2);c.fill()}}
takeDamage(d){this.hp-=d;if(this.hp<=0){this.hp=0;return true}return false}}

class Zombie{
constructor(t,r,g){const d=C.zombies[t];this.type=t;this.row=r;this.hp=d.hp;this.maxHp=d.hp;this.spd=d.spd;this.dmg=d.dmg;this.rate=d.rate;this.x=g.canvas.width+30;this.y=C.grid.oy+r*C.grid.ch+C.grid.ch/2;this.af=0;this.at=0;this.eat=false;this.lastEat=0;this.target=null;this.slowed=0;this.dead=false;this.jumped=false}
update(dt,g){if(this.hp<=0){this.dead=true;return};this.at+=dt;if(this.at>120){this.af=(this.af+1)%30;this.at=0};if(this.slowed>0)this.slowed=Math.max(0,this.slowed-dt);const sp=this.slowed>0?this.spd*0.5:this.spd;this.target=null;for(const p of g.plants){if(p.row===this.row&&p.hp>0&&p.type!=='cherrybomb'&&!p.done){const px=C.grid.ox+p.col*C.grid.cw+C.grid.cw/2;if(Math.abs(this.x-px)<50){this.target=p;break}}};if(this.target){if(this.type==='pole'&&!this.jumped){this.jumped=true;this.x=this.target.x+30;if(this.x>g.canvas.width-20)this.x=g.canvas.width-20;this.target=null;this.eat=false}else{this.eat=true;if(g.time-this.lastEat>=this.rate){this.lastEat=g.time;if(this.target.takeDamage(this.dmg)){g.removePlant(this.target);this.target=null;this.eat=false}}}}else{this.eat=false;this.x-=sp*(dt/16.67)};if(this.x<-20)g.lose()}
takeDamage(d){this.hp-=d;if(this.hp<=0){this.dead=true;return true}return false}
applySlow(d){this.slowed=Math.max(this.slowed,d)}
draw(c){if(this.dead)return;const zx=this.x,zy=this.y+(this.eat?2:0)-(this.slowed>0?2:0),wb=Math.sin(this.af*0.4)*3,bob=this.eat?0:wb;c.save();c.fillStyle=C.zombies[this.type].color;c.beginPath();c.ellipse(zx,zy+bob,18,25,0,0,Math.PI*2);c.fill();switch(this.type){case'cone':c.fillStyle='#d97706';c.beginPath();c.moveTo(zx,zy-30+bob);c.lineTo(zx-15,zy-5+bob);c.lineTo(zx+15,zy-5+bob);c.closePath();c.fill();c.strokeStyle='#b45309';c.lineWidth=2;c.stroke();break;case'bucket':c.fillStyle='#6b7280';c.fillRect(zx-18,zy-32+bob,36,30);c.fillStyle='#9ca3af';c.fillRect(zx-16,zy-30+bob,32,4);c.fillRect(zx-16,zy-18+bob,32,4);break;case'flag':c.fillStyle='#7c3aed';c.beginPath();c.moveTo(zx,zy-28+bob);c.lineTo(zx-3,zy-10+bob);c.lineTo(zx+12,zy-16+bob);c.closePath();c.fill();c.strokeStyle='#5b21b6';c.lineWidth=1;c.beginPath();c.moveTo(zx,zy-28+bob);c.lineTo(zx,zy-2+bob);c.stroke();break;case'pole':c.strokeStyle='#9a3412';c.lineWidth=3;c.beginPath();c.moveTo(zx-18,zy-20+bob);c.lineTo(zx+18,zy+20+bob);c.stroke();break;default:c.fillStyle='#4a3728';c.beginPath();c.arc(zx,zy-22+bob,14,Math.PI,0);c.fill()};c.fillStyle='#8B7355';c.beginPath();c.arc(zx,zy-5+bob,15,0,Math.PI*2);c.fill();c.fillStyle='#ef4444';c.shadowColor='#ef4444';c.shadowBlur=6;c.beginPath();c.arc(zx-6,zy-8+bob,3,0,Math.PI*2);c.fill();c.beginPath();c.arc(zx+6,zy-8+bob,3,0,Math.PI*2);c.fill();c.shadowBlur=0;c.fillStyle='#5c3d2e';c.beginPath();if(this.eat)c.arc(zx,zy+6+bob,5,0,Math.PI);else c.arc(zx,zy+4+bob,4,.1,Math.PI-.1);c.fill();c.strokeStyle='#8B7355';c.lineWidth=4;c.beginPath();c.moveTo(zx-18,zy+2+bob);c.lineTo(zx-28,zy+8+(this.eat?5:0)+bob);c.stroke();c.beginPath();c.moveTo(zx+18,zy+2+bob);c.lineTo(zx+28,zy+8+(this.eat?5:0)+bob);c.stroke();c.strokeStyle='#5c3d2e';c.lineWidth=5;const la=this.eat?0:Math.sin(this.af*0.4)*5;c.beginPath();c.moveTo(zx-6,zy+22+bob);c.lineTo(zx-6+la,zy+38+bob);c.stroke();c.beginPath();c.moveTo(zx+6,zy+22+bob);c.lineTo(zx+6-la,zy+38+bob);c.stroke();if(this.slowed>0){c.fillStyle='rgba(96,165,250,.3)';c.beginPath();c.arc(zx,zy+bob,40,0,Math.PI*2);c.fill();c.fillStyle='rgba(255,255,255,.3)';const ta=Date.now()*0.003;for(let i=0;i<3;i++){const a=ta+i*Math.PI*2/3;c.beginPath();c.arc(zx+Math.cos(a)*28,zy-10+bob+Math.sin(a)*15,2,0,Math.PI*2);c.fill()}};c.restore();if(this.hp<this.maxHp){const bw=40,bh=4,bx=zx-bw/2,by=zy-40+bob,r=this.hp/this.maxHp;c.fillStyle='rgba(0,0,0,.5)';c.fillRect(bx,by,bw,bh);c.fillStyle=r>.5?'#f87171':r>.25?'#fb923c':'#ef4444';c.fillRect(bx,by,bw*r,bh)}}}

class Proj{
constructor(x,y,r,s){this.x=x;this.y=y;this.row=r;this.snow=s;this.spd=C.proj.spd;this.sz=C.proj.size;this.active=true;this.trail=[]}
update(dt,g){this.x+=this.spd*(dt/16.67);this.trail.push({x:this.x,y:this.y,l:8});if(this.trail.length>5)this.trail.shift();this.trail=this.trail.filter(t=>{t.l-=dt/16.67;return t.l>0});for(const z of g.zombies){if(z.dead||z.row!==this.row)continue;if(Math.abs(this.x-z.x)<25){z.takeDamage(this.snow?C.plants.snowpea.dmg:C.plants.peashooter.dmg);if(this.snow)z.applySlow(3e3);this.active=false;g.hitEff.push({x:this.x,y:this.y,t:200,color:this.snow?'#93c5fd':'#4ade80'});break}};if(this.x>g.canvas.width+20)this.active=false}
draw(c){if(!this.active)return;for(const t of this.trail){const a=t.l/8;c.fillStyle=this.snow?'rgba(147,197,253,'+(a*0.3)+')':'rgba(34,197,94,'+(a*0.3)+')';c.beginPath();c.arc(t.x,t.y,this.sz*0.6*a,0,Math.PI*2);c.fill()};c.save();const g=c.createRadialGradient(this.x,this.y,1,this.x,this.y,this.sz);g.addColorStop(0,this.snow?'#fff':'#86efac');g.addColorStop(.5,this.snow?'#93c5fd':'#22c55e');g.addColorStop(1,this.snow?'#60a5fa':'#16a34a');c.fillStyle=g;c.shadowColor=this.snow?'#60a5fa':'#22c55e';c.shadowBlur=8;c.beginPath();c.arc(this.x,this.y,this.sz,0,Math.PI*2);c.fill();c.restore()}}

class Sun{
constructor(x,y,fs,g){this.x=x;this.y=fs?y:-30;this.targetY=y+(fs>0?80+Math.random()*60:0);this.val=C.sun.val;this.sz=C.sun.size;this.fall=C.sun.fallSpd;this.life=C.sun.life;this.born=g?g.time:0;this.fs=fs;this.collect=false;this.collecting=false;this.cTarget=null;this.cSpd=6;this.active=true;this.pulse=0}
update(dt,g){if(!this.active)return;if(this.collecting&&this.cTarget){const dx=this.cTarget.x-this.x,dy=this.cTarget.y-this.y,dist=Math.sqrt(dx*dx+dy*dy);if(dist<10){this.active=false;g.addSun(this.val);return};this.x+=dx/dist*this.cSpd*(dt/16.67);this.y+=dy/dist*this.cSpd*(dt/16.67);return};if(this.fs>0&&this.y<this.targetY){this.y+=this.fall*(dt/16.67);if(this.y>=this.targetY)this.y=this.targetY};if(g&&g.time-this.born>this.life)this.active=false;this.pulse+=dt*0.003}
draw(c){if(!this.active)return;c.save();const px=this.x,py=this.y,ps=Math.sin(this.pulse)*2;const g=c.createRadialGradient(px,py,2,px,py,this.sz+15+ps);g.addColorStop(0,'rgba(251,191,36,.6)');g.addColorStop(.5,'rgba(251,191,36,.2)');g.addColorStop(1,'rgba(251,191,36,0)');c.fillStyle=g;c.beginPath();c.arc(px,py,this.sz+15+ps,0,Math.PI*2);c.fill();const g2=c.createRadialGradient(px-5,py-5,2,px,py,this.sz+ps);g2.addColorStop(0,'#fef3c7');g2.addColorStop(.5,'#fbbf24');g2.addColorStop(1,'#f59e0b');c.fillStyle=g2;c.shadowColor='#fbbf24';c.shadowBlur=15;c.beginPath();c.arc(px,py,this.sz+ps,0,Math.PI*2);c.fill();c.shadowBlur=0;c.strokeStyle='rgba(251,191,36,.4)';c.lineWidth=2;for(let i=0;i<8;i++){const a=i/8*Math.PI*2+this.pulse;c.beginPath();c.moveTo(px+Math.cos(a)*(this.sz+5+ps),py+Math.sin(a)*(this.sz+5+ps));c.lineTo(px+Math.cos(a)*(this.sz+12+ps),py+Math.sin(a)*(this.sz+12+ps));c.stroke()};c.fillStyle='rgba(255,255,255,.4)';c.beginPath();c.arc(px-6,py-6,this.sz*0.3,0,Math.PI*2);c.fill();c.restore()}
contains(mx,my){const dx=this.x-mx,dy=this.y-my;return dx*dx+dy*dy<(this.sz+20)*(this.sz+20)}}

class PlantFood{
constructor(x,y){this.x=x;this.y=y;this.sz=14;this.active=true;this.pulse=0;this.targetY=y}
update(dt){if(!this.active)return;this.pulse+=dt*0.004}
draw(c){if(!this.active)return;c.save();const px=this.x,py=this.y,ps=Math.sin(this.pulse)*3;const g=c.createRadialGradient(px,py,2,px,py,this.sz+12+ps);g.addColorStop(0,'rgba(168,85,247,.5)');g.addColorStop(1,'rgba(168,85,247,0)');c.fillStyle=g;c.beginPath();c.arc(px,py,this.sz+12+ps,0,Math.PI*2);c.fill();const g2=c.createRadialGradient(px,py,2,px,py,this.sz+ps);g2.addColorStop(0,'#f3e8ff');g2.addColorStop(.5,'#a78bfa');g2.addColorStop(1,'#7c3aed');c.fillStyle=g2;c.shadowColor='#a78bfa';c.shadowBlur=20;c.beginPath();c.arc(px,py,this.sz+ps,0,Math.PI*2);c.fill();c.shadowBlur=0;c.fillStyle='rgba(255,255,255,.6)';c.beginPath();c.arc(px-4,py-4,4,0,Math.PI*2);c.fill();c.fillStyle='#fff';c.font='bold 12px sans-serif';c.textAlign='center';c.textBaseline='middle';c.fillText('✨',px,py+2);c.restore()}
contains(mx,my){return(Math.abs(this.x-mx)<this.sz+16)&&(Math.abs(this.y-my)<this.sz+16)}}

class Mower{
constructor(row){this.row=row;this.active=true;this.triggered=false;this.x=0;this.y=C.grid.oy+row*C.grid.ch+C.grid.ch/2;this.spd=C.mowerSpd}
update(dt,g){if(!this.triggered)return;this.x+=this.spd*(dt/16.67);for(const z of g.zombies){if(z.row===this.row&&!z.dead&&Math.abs(z.x-this.x)<30)z.takeDamage(1e4)};if(this.x>g.canvas.width+50)this.active=false}
draw(c){if(!this.active)return;c.save();const mx=this.triggered?this.x:0,my=this.y;c.fillStyle='#78716c';c.roundRect(mx-16,my-14,32,28,6);c.fill();c.fillStyle='#44403c';c.beginPath();c.arc(mx,my+10,12,0,Math.PI,0);c.fill();c.fillStyle='#a8a29e';c.fillRect(mx-2,my-12,4,8);c.fillStyle='#ef4444';c.beginPath();c.arc(mx,my-16,8,0,Math.PI*2);c.fill();if(this.triggered){c.fillStyle='rgba(255,255,255,.3)';c.beginPath();c.arc(mx,my-16,14,0,Math.PI*2);c.fill()};c.restore()}
checkTrigger(zombies){if(this.triggered)return;for(const z of zombies){if(z.row===this.row&&!z.dead&&z.x<30){this.triggered=true;return true}};return false}}
