// ====== 游戏引擎 ======
class Game{
constructor(){this.canvas=document.getElementById('game-canvas');this.ctx=this.canvas.getContext('2d');this.state='menu';this.reset()}
reset(){this.time=0;this.spd=1;this.sunCount=0;this.curWave=0;this.waveAct=false;this.waveTim=0;this.allDone=false;this.zwAlive=0;this.plants=[];this.zombies=[];this.projs=[];this.suns=[];this.pfItems=[];this.mowers=[];this.hitEff=[];this.pfCount=0;this.pfActive=false;this.grid=Array.from({length:C.grid.rows},()=>Array(C.grid.cols).fill(null));this.selPlant=null;this.cds={};this.skySunTim=0;this.pfTim=0;this.mx=-1;this.my=-1;this.lastF=0;this.reqId=null;this.waveNotif=null;this.cfg=null;this.curLevel=0;this.overlay=null}
init(){const tw=C.grid.cols*C.grid.cw,th=C.grid.rows*C.grid.ch;C.grid.ox=(this.canvas.width-tw)/2;C.grid.oy=(this.canvas.height-th)/2;this.overlay=document.createElement('div');this.overlay.className='pause-overlay';this.overlay.innerHTML='<span class=pause-text>⏸️ 已暂停</span>';document.getElementById('game-container').appendChild(this.overlay)}
startLevel(lvIdx){this.reset();this.curLevel=lvIdx;const lv=C.levels[lvIdx];this.cfg=lv;this.state='playing';this.sunCount=lv.startSun;this.time=0;this.curWave=0;this.allDone=false;this.zwAlive=0;this.skySunTim=3e3;this.pfTim=0;this.pfCount=0;this.pfActive=false;this.mowers=[];for(let r=0;r<C.grid.rows;r++)this.mowers.push(new Mower(r));buildSelector(lv.avail);this.cds={};const pl=Object.keys(C.plants);for(const k of pl)this.cds[k]=0;this.waveTim=lv.waveDelay;document.getElementById('level-name').textContent='🌻'+lv.name;document.getElementById('pf-display').style.display=lvIdx>0?'flex':'none';this.updateUI();this.clearActive();if(this.reqId)cancelAnimationFrame(this.reqId);this.lastF=performance.now();this.loop(this.lastF)}
loop(ts){if(this.state==='menu')return;const dt=Math.min(ts-this.lastF,50);this.lastF=ts;if(this.state==='playing')this.update(dt*this.spd);this.render();this.reqId=requestAnimationFrame(t=>this.loop(t))}
update(dt){this.time+=dt;this.updateWaves(dt);this.skySunTim+=dt;if(this.skySunTim>=this.cfg.skyInt){this.skySunTim=0;this.spawnSkySun()};this.pfTim+=dt;if(this.pfTim>=C.pf.dropInt&&this.curLevel>0){this.pfTim=0;this.spawnPF()};for(const p of this.plants)p.update(dt,this);for(const p of this.projs)p.update(dt,this);this.projs=this.projs.filter(p=>p.active);for(const z of this.zombies)z.update(dt,this);this.zombies=this.zombies.filter(z=>!z.dead);for(const s of this.suns)s.update(dt,this);this.suns=this.suns.filter(s=>s.active);for(const p of this.pfItems)p.update(dt);this.pfItems=this.pfItems.filter(p=>p.active);for(const m of this.mowers){m.checkTrigger(this.zombies);m.update(dt,this)};this.mowers=this.mowers.filter(m=>m.active);for(const e of this.hitEff)e.t-=dt;this.hitEff=this.hitEff.filter(e=>e.t>0);for(const k in this.cds){if(this.cds[k]>0){this.cds[k]-=dt;if(this.cds[k]<0)this.cds[k]=0}};this.zwAlive=this.zombies.length;if(this.allDone&&this.zwAlive===0)this.win();this.updateUI();this.updateCards()}
updateWaves(dt){if(this.allDone)return;if(!this.waveAct){this.waveTim-=dt;if(this.waveTim<=0)this.startWave();return};const w=this.cfg.waves[this.curWave];let all=true;for(const zd of w){if(!zd._s){all=false;if(this.waveTim>=zd.d){this.spawnZ(zd.t,zd.r);zd._s=true}}};this.waveTim+=dt;if(all&&this.zwAlive===0){this.waveAct=false;this.curWave++;if(this.curWave>=this.cfg.waves.length)this.allDone=true;else this.waveTim=this.cfg.waveDelay}}
startWave(){if(this.curWave>=this.cfg.waves.length)return;this.waveAct=true;this.waveTim=0;for(const zd of this.cfg.waves[this.curWave])zd._s=false;this.showNotif('🌊 第'+(this.curWave+1)+'波 来袭！')}
spawnZ(t,r){this.zombies.push(new Zombie(t,r,this))}
spawnSkySun(){const col=Math.floor(Math.random()*C.grid.cols);this.suns.push(new Sun(C.grid.ox+col*C.grid.cw+C.grid.cw/2+(Math.random()-.5)*60,-20,1,this))}
spawnPF(){const col=Math.floor(Math.random()*C.grid.cols);const x=C.grid.ox+col*C.grid.cw+C.grid.cw/2;const pf=new PlantFood(x,C.grid.oy-20);pf.targetY=C.grid.oy+Math.random()*C.grid.rows*C.grid.ch;this.pfItems.push(pf)}
placePlant(t,r,c){if(!C.plants[t])return false;const d=C.plants[t];if(this.sunCount<d.cost||this.cds[t]>0||this.grid[r][c]!==null)return false;if(this.pfActive&&(t==='peashooter'||t==='snowpea'||t==='sunflower')){this.pfActive=false;const p=new Plant(t,r,c);p.boosted=C.pf.boostDur;this.plants.push(p);this.grid[r][c]=p;this.hitEff.push({x:p.x,y:p.y,t:400,color:'#a78bfa',big:true});document.getElementById('pf-count').textContent='0';this.updateCards();return true};if(d.cat==='instant'&&t==='cherrybomb'){if(this.sunCount<d.cost)return false;this.sunCount-=d.cost;this.cds[t]=d.cd;this.explodeCherry(r,c);return true};this.sunCount-=d.cost;const p=new Plant(t,r,c);this.plants.push(p);this.grid[r][c]=p;this.cds[t]=d.cd;this.hitEff.push({x:p.x,y:p.y,t:300,color:d.color});return true}
explodeCherry(r,c){const cx=C.grid.ox+c*C.grid.cw+C.grid.cw/2,cy=C.grid.oy+r*C.grid.ch+C.grid.ch/2;this.hitEff.push({x:cx,y:cy,t:500,color:'#ef4444',big:true});this.hitEff.push({x:cx-50,y:cy-50,t:300,color:'#f97316'});this.hitEff.push({x:cx+50,y:cy-50,t:300,color:'#f97316'});this.hitEff.push({x:cx-50,y:cy+50,t:300,color:'#f97316'});this.hitEff.push({x:cx+50,y:cy+50,t:300,color:'#f97316'});for(let dr=-1;dr<=1;dr++){for(let dc=-1;dc<=1;dc++){const nr=r+dr,nc=c+dc;if(nr<0||nr>=C.grid.rows||nc<0||nc>=C.grid.cols)continue;for(const z of this.zombies)if(z.row===nr&&!z.dead)z.takeDamage(1e4)}}}
removePlant(p){const i=this.plants.indexOf(p);if(i!==-1){this.plants.splice(i,1);this.grid[p.row][p.col]=null}}
addSun(a){this.sunCount+=a;this.updateUI()}
collectPF(){this.pfCount++;this.pfActive=true;document.getElementById('pf-count').textContent='1'}
lose(){this.state='lose';this.overlay.classList.remove('show');document.getElementById('game-screen').classList.add('hidden');document.getElementById('lose-screen').classList.remove('hidden')}
win(){setTimeout(()=>{this.state='win';this.overlay.classList.remove('show');document.getElementById('game-screen').classList.add('hidden');document.getElementById('win-screen').classList.remove('hidden');document.getElementById('win-msg').textContent=C.levels[this.curLevel].name+' 通关！';document.getElementById('next-level-btn').style.display=this.curLevel<C.levels.length-1?'inline-block':'none';if(this.curLevel<C.levels.length-1)unlockLv(this.curLevel+1)},1500)}
render(){const c=this.ctx,{width,height}=this.canvas;c.clearRect(0,0,width,height);this.drawLawn(c);this.drawGrid(c);this.drawProgress(c);this.drawPlace(c);for(const m of this.mowers)m.draw(c);for(const p of this.plants)p.draw(c);for(const p of this.projs)p.draw(c);for(const z of this.zombies)z.draw(c);for(const s of this.suns)s.draw(c);for(const p of this.pfItems)p.draw(c);this.drawHit(c);this.drawNotif(c)}
drawLawn(c){const o=C.grid;const bg=c.createLinearGradient(0,0,0,this.canvas.height);bg.addColorStop(0,'#2d5016');bg.addColorStop(.5,'#3a6b1e');bg.addColorStop(1,'#2d5016');c.fillStyle=bg;c.fillRect(0,0,this.canvas.width,this.canvas.height);for(let r=0;r<o.rows;r++){for(let c2=0;c2<o.cols;c2++){const x=o.ox+c2*o.cw,y=o.oy+r*o.ch,lt=(r+c2)%2===0;c.fillStyle=lt?'#4a8f2c':'#3f7e25';c.fillRect(x,y,o.cw,o.ch);c.fillStyle=lt?'rgba(255,255,255,.03)':'rgba(0,0,0,.03)';const sd=(r*7+c2*11)%5;for(let i=0;i<sd;i++)c.beginPath(),c.arc(x+15+(i*23+r*7)%(o.cw-30),y+15+(i*17+c2*11)%(o.ch-30),2,0,Math.PI*2),c.fill()}};c.fillStyle='#5c4033';c.fillRect(0,o.oy-4,this.canvas.width,4);c.fillRect(0,o.oy+o.rows*o.ch,this.canvas.width,4);c.fillRect(o.ox-4,o.oy,4,o.rows*o.ch);c.fillRect(o.ox+o.cols*o.cw,o.oy,4,o.rows*o.ch);c.fillStyle='rgba(139,90,43,.3)';c.fillRect(0,o.oy,o.ox,o.rows*o.ch);c.fillStyle='rgba(139,90,43,.4)';for(let i=0;i<6;i++)c.fillRect(10,o.oy+20+60*i,30,40);c.fillStyle='rgba(139,90,43,.15)';c.fillRect(o.ox+o.cols*o.cw,o.oy,this.canvas.width-o.ox-o.cols*o.cw,o.rows*o.ch)}
drawGrid(c){const o=C.grid;c.strokeStyle='rgba(255,255,255,.08)';c.lineWidth=1;for(let i=0;i<=o.cols;i++){const x=o.ox+i*o.cw;c.beginPath();c.moveTo(x,o.oy);c.lineTo(x,o.oy+o.rows*o.ch);c.stroke()};for(let i=0;i<=o.rows;i++){const y=o.oy+i*o.ch;c.beginPath();c.moveTo(o.ox,y);c.lineTo(o.ox+o.cols*o.cw,y);c.stroke()}}
drawProgress(c){const o=C.grid;const total=this.cfg.waves.length,cur=this.curWave;const bw=o.cols*o.cw-40,bh=6,bx=o.ox+20,by=o.oy+o.rows*o.ch+8;c.fillStyle='rgba(0,0,0,.4)';c.roundRect(bx,by,bw,bh,3);c.fill();const p=Math.min(cur/total,1);c.fillStyle='#4ade80';c.roundRect(bx,by,bw*p,bh,3);c.fill();c.fillStyle='rgba(255,255,255,.5)';c.font='10px sans-serif';c.textAlign='center';c.textBaseline='middle';c.fillText('波次 '+Math.min(cur+1,total)+'/'+total,o.ox+o.cols*o.cw/2,by+3+bh/2)}
drawPlace(c){if(!this.selPlant||this.mx<0||this.my<0)return;const o=C.grid,col=Math.floor((this.mx-o.ox)/o.cw),row=Math.floor((this.my-o.oy)/o.ch);if(row<0||row>=o.rows||col<0||col>=o.cols)return;const x=o.ox+col*o.cw,y=o.oy+row*o.ch,ok=this.grid[row][col]===null&&this.sunCount>=C.plants[this.selPlant].cost&&this.cds[this.selPlant]<=0;c.fillStyle=ok?'rgba(74,222,128,.2)':'rgba(248,113,113,.2)';c.fillRect(x,y,o.cw,o.ch);c.strokeStyle=ok?'rgba(74,222,128,.5)':'rgba(248,113,113,.5)';c.lineWidth=2;c.setLineDash([5,5]);c.strokeRect(x,y,o.cw,o.ch);c.setLineDash([])}
drawHit(c){for(const e of this.hitEff){const a=Math.min(e.t/500,.7);if(e.big){const r=e.color==='#a78bfa'?50:40;c.fillStyle=e.color+Math.floor(a*255).toString(16).padStart(2,'0');c.beginPath();c.arc(e.x,e.y,r*(1-e.t/500),0,Math.PI*2);c.fill();c.strokeStyle='rgba(255,255,255,'+(a*0.4)+')';c.lineWidth=3;c.beginPath();c.arc(e.x,e.y,r+10*(1-e.t/500),0,Math.PI*2);c.stroke()}else{c.fillStyle=e.color+Math.floor(a*200).toString(16).padStart(2,'0');c.beginPath();c.arc(e.x,e.y,12*(1-e.t/300),0,Math.PI*2);c.fill()}}}
showNotif(t){this.waveNotif={text:t,timer:2e3,alpha:0}}
drawNotif(c){if(!this.waveNotif)return;const n=this.waveNotif;n.timer-=16.67;if(n.timer>1500)n.alpha=Math.min(n.alpha+.05,1);else if(n.timer>500)n.alpha=1;else n.alpha=Math.max(n.alpha-.05,0);if(n.timer<=0){this.waveNotif=null;return};c.save();c.globalAlpha=n.alpha;c.fillStyle='rgba(0,0,0,.6)';const tw=c.measureText(n.text).width;c.roundRect(this.canvas.width/2-tw/2-30,this.canvas.height/2-30,tw+60,60,12);c.fill();c.fillStyle='#fff';c.font='bold 22px "Microsoft YaHei","PingFang SC","Hiragino Sans GB",sans-serif';c.textAlign='center';c.textBaseline='middle';c.fillText(n.text,this.canvas.width/2,this.canvas.height/2);c.restore()}
handleClick(mx,my){if(this.state!=='playing')return;for(const s of this.suns){if(s.active&&!s.collecting&&s.contains(mx,my)){s.collecting=true;const el=document.querySelector('.sd'),rect=el.getBoundingClientRect(),cr=this.canvas.getBoundingClientRect();s.cTarget={x:rect.left-cr.left+rect.width/2,y:rect.top-cr.top+rect.height/2};return}};for(const p of this.pfItems){if(p.active&&p.contains(mx,my)){this.collectPF();p.active=false;return}};if(this.pfActive){const o=C.grid,col=Math.floor((mx-o.ox)/o.cw),row=Math.floor((my-o.oy)/o.ch);if(row>=0&&row<o.rows&&col>=0&&col<o.cols&&this.grid[row][col]!==null){const pl=this.grid[row][col];if(pl.type==='peashooter'||pl.type==='snowpea'||pl.type==='sunflower'){pl.boosted=C.pf.boostDur;this.pfActive=false;this.pfCount=0;document.getElementById('pf-count').textContent='0';this.hitEff.push({x:pl.x,y:pl.y,t:400,color:'#a78bfa',big:true});return}}};if(!this.selPlant)return;const o=C.grid,col=Math.floor((mx-o.ox)/o.cw),row=Math.floor((my-o.oy)/o.ch);if(this.placePlant(this.selPlant,row,col)){this.selPlant=null;this.clearActive()}}
handleMove(mx,my){this.mx=mx;this.my=my}
updateUI(){document.getElementById('sun-count').textContent=this.sunCount;document.getElementById('wave-info').textContent=this.allDone?'最终波次':'第'+(this.curWave+1)+'/'+this.cfg.waves.length+'波';document.getElementById('zombie-count').textContent=this.zwAlive}
updateCards(){document.querySelectorAll('.plant-card').forEach(card=>{const t=card.dataset.plant,c=parseInt(card.dataset.cost),aff=this.sunCount>=c,cl=this.cds[t]>0;card.classList.toggle('disabled',!aff||cl);let el=card.querySelector('.cd-overlay');if(cl){if(!el){el=document.createElement('div');el.className='cd-overlay';card.appendChild(el)};el.textContent=Math.ceil(this.cds[t]/1e3)+'s';card.classList.add('on-cd')}else{if(el)el.remove();card.classList.remove('on-cd')}})}
setSelPlant(t){if(this.sunCount<C.plants[t].cost||this.cds[t]>0||this.state!=='playing')return;if(this.selPlant===t){this.selPlant=null;this.clearActive()}else{this.selPlant=t;this.clearActive();const el=document.querySelector('.plant-card[data-plant="'+t+'"]');if(el)el.classList.add('active')}}
clearActive(){document.querySelectorAll('.plant-card').forEach(c=>c.classList.remove('active'))}
togglePause(){if(this.state==='playing'){this.state='paused';this.overlay.classList.add('show')}else if(this.state==='paused'){this.state='playing';this.overlay.classList.remove('show')}}
toggleSpeed(){this.spd=this.spd===1?2:1;document.getElementById('speed-btn').textContent=this.spd+'×';document.getElementById('speed-btn').classList.toggle('active',this.spd===2)}
}
